image: alpine/edge
secrets:
  - 6224e118-9553-4475-8b41-0a69a2b22d8a
sources:
  - git@git.sr.ht/~bugwhisperer/fern.nvim
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      # This is for not having to cd into your <repo> for each task
      echo 'cd fern.nvim' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:bugwhisperer418/fern.nvim.git
